# Generated by Django 5.2.2 on 2025-06-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_adminprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dishrating',
            unique_together=set(),
        ),
    ]
