# Generated by Django 5.2.2 on 2025-07-05 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20250617_1346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_preparing', 'Order Preparing'), ('order_ready', 'Order Ready'), ('order_delivered', 'Order Delivered'), ('stock_low', 'Stock Low'), ('payment_received', 'Payment Received')], max_length=20, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Total Orders')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Revenue')),
                ('popular_dishes', models.JSONField(default=dict, verbose_name='Popular Dishes')),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Average Order Value')),
            ],
            options={
                'verbose_name': 'Order Analytics',
                'verbose_name_plural': 'Order Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='dish',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, verbose_name='Low Stock Alert'),
        ),
        migrations.AddField(
            model_name='dish',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='dish',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Quantity'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_at'], name='restaurant__created_46a948_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='restaurant__is_acti_949025_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='restaurant__slug_9b53c7_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['category', 'is_available'], name='restaurant__categor_0eb496_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['created_at'], name='restaurant__created_404629_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['price'], name='restaurant__price_06e75c_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['slug'], name='restaurant__slug_f1731b_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['stock_quantity'], name='restaurant__stock_q_052d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='restaurant__order_d_89894b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='restaurant__status_d66ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='restaurant__payment_958ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'order_date'], name='restaurant__custome_555d59_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='orderanalytics',
            index=models.Index(fields=['date'], name='restaurant__date_4a2269_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderanalytics',
            unique_together={('date',)},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='restaurant__user_id_9e6f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='restaurant__created_9d25c7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='restaurant__notific_f95daa_idx'),
        ),
    ]
