# Generated by Django 5.2.4 on 2025-07-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_notification_orderanalytics_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Email Verification Code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Verified'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Phone Verified'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Phone Verification Code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='verification_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification Code Expires At'),
        ),
    ]
