# Generated by Django 5.2.2 on 2025-07-10 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_customer_email_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_verification_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='verification_code_expires_at',
        ),
    ]
