# Generated by Django 5.2.2 on 2025-07-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_add_contact_message_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, default='No Subject Provided', max_length=255, verbose_name='Subject'),
        ),
    ]
